package com.studiorad.bluetticontrol;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
    LinearLayout list; TextView status; EditText url, token; final ArrayList<JSONObject> entities=new ArrayList<>(); String base="", tok="";
    int blue=Color.rgb(21,101,192), bg=Color.rgb(245,247,251);
    public void onCreate(Bundle b){super.onCreate(b); SharedPreferences p=getSharedPreferences("cfg",0); base=p.getString("url",""); tok=p.getString("token",""); build(); if(!base.isEmpty()&&!tok.isEmpty()) refresh();}
    TextView tv(String t,int sp,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(c);v.setPadding(20,12,20,8);return v;}
    Button btn(String t){Button b=new Button(this);b.setText(t);b.setAllCaps(false);return b;}
    void build(){ScrollView sv=new ScrollView(this); LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);sv.addView(root); root.addView(tv("Bluetti Control",26,Color.rgb(20,30,45))); root.addView(tv("Controle via Home Assistant. Use token Long-Lived Access Token.",14,Color.DKGRAY)); url=new EditText(this);url.setHint("http://192.168.1.72:8123");url.setText(base);root.addView(url); token=new EditText(this);token.setHint("Token do Home Assistant");token.setText(tok);root.addView(token); LinearLayout row=new LinearLayout(this);row.setPadding(10,6,10,6);row.setOrientation(LinearLayout.HORIZONTAL); Button save=btn("Salvar"); Button r=btn("Atualizar"); row.addView(save,new LinearLayout.LayoutParams(0,-2,1));row.addView(r,new LinearLayout.LayoutParams(0,-2,1));root.addView(row); status=tv("Status: aguardando",15,Color.DKGRAY);root.addView(status); list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list); save.setOnClickListener(v->{base=url.getText().toString().trim().replaceAll("/$","");tok=token.getText().toString().trim();getSharedPreferences("cfg",0).edit().putString("url",base).putString("token",tok).apply();refresh();}); r.setOnClickListener(v->refresh()); setContentView(sv);}
    void refresh(){status.setText("Status: conectando...");list.removeAllViews();new Thread(()->{try{String res=get("/api/states");JSONArray arr=new JSONArray(res);entities.clear();for(int i=0;i<arr.length();i++){JSONObject o=arr.getJSONObject(i);String id=o.getString("entity_id");String name=o.optJSONObject("attributes").optString("friendly_name",""); if(id.toLowerCase().contains("bluetti")||name.toLowerCase().contains("bluetti")){entities.add(o);}} runOnUiThread(()->render());}catch(Exception e){runOnUiThread(()->status.setText("Offline/erro: "+e.getMessage()));}}).start();}
    void render(){int online=0; for(JSONObject o:entities) if(!o.optString("state").equals("unavailable")) online++; status.setText("Online: "+online+" / "+entities.size()+" entidades Bluetti"); if(entities.isEmpty()) list.addView(tv("Nenhum dispositivo Bluetti encontrado. Confira se a integração no Home Assistant criou entidades com Bluetti no nome.",15,Color.DKGRAY)); for(JSONObject o:entities) card(o);}
    void card(JSONObject o){try{String id=o.getString("entity_id"), state=o.optString("state"), name=o.optJSONObject("attributes").optString("friendly_name",id); LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,14,18,14);c.setBackgroundColor(Color.WHITE); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(14,10,14,10);list.addView(c,lp); c.addView(tv(name,18,Color.rgb(20,30,45))); c.addView(tv(id+"  •  "+state,13,state.equals("unavailable")?Color.RED:Color.DKGRAY)); if(id.startsWith("switch.")){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);Button on=btn("Ligar");Button off=btn("Desligar");row.addView(on,new LinearLayout.LayoutParams(0,-2,1));row.addView(off,new LinearLayout.LayoutParams(0,-2,1));c.addView(row);on.setOnClickListener(v->service("switch","turn_on",id,null));off.setOnClickListener(v->service("switch","turn_off",id,null));} else if(id.startsWith("select.")){JSONArray opts=o.optJSONObject("attributes").optJSONArray("options"); if(opts!=null){Spinner sp=new Spinner(this);ArrayList<String> a=new ArrayList<>();for(int i=0;i<opts.length();i++)a.add(opts.getString(i));sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,a));Button set=btn("Aplicar opção");c.addView(sp);c.addView(set);set.setOnClickListener(v->service("select","select_option",id,sp.getSelectedItem().toString()));}} }catch(Exception ignored){}}
    String get(String path)throws Exception{HttpURLConnection h=(HttpURLConnection)new URL(base+path).openConnection();h.setRequestProperty("Authorization","Bearer "+tok);h.setRequestProperty("Content-Type","application/json");h.setConnectTimeout(8000);h.setReadTimeout(12000);return read(h);} 
    void service(String domain,String service,String entity,String option){new Thread(()->{try{JSONObject body=new JSONObject();body.put("entity_id",entity);if(option!=null)body.put("option",option);HttpURLConnection h=(HttpURLConnection)new URL(base+"/api/services/"+domain+"/"+service).openConnection();h.setRequestMethod("POST");h.setDoOutput(true);h.setRequestProperty("Authorization","Bearer "+tok);h.setRequestProperty("Content-Type","application/json");h.getOutputStream().write(body.toString().getBytes(StandardCharsets.UTF_8));read(h);runOnUiThread(()->{Toast.makeText(this,"Comando enviado",Toast.LENGTH_SHORT).show();refresh();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Erro: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
    String read(HttpURLConnection h)throws Exception{int code=h.getResponseCode();InputStream in=code>=400?h.getErrorStream():h.getInputStream();BufferedReader br=new BufferedReader(new InputStreamReader(in));StringBuilder sb=new StringBuilder();String line;while((line=br.readLine())!=null)sb.append(line);if(code>=400)throw new Exception(code+" "+sb);return sb.toString();}
}
