package com.studiorad.bluetticontrol;

import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.view.*;
import android.widget.*;

public class ModernMainActivity extends MainActivity {
    int bg = Color.rgb(238,242,247), white = Color.WHITE, text = Color.rgb(26,28,30), muted = Color.rgb(100,116,139);
    int green = Color.rgb(0,177,93), greenDark = Color.rgb(0,109,55), blue = Color.rgb(47,121,201), orange = Color.rgb(245,158,11), purple = Color.rgb(155,81,224), red = Color.rgb(225,29,72);
    TextView heroName, heroSoc, heroTime, statBattery, statInput, statOutput, statDc;

    @Override public void onCreate(Bundle b){ super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(244,252,241)); getWindow().setNavigationBarColor(Color.rgb(232,240,229)); if(android.os.Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR); try{ if(android.os.Build.VERSION.SDK_INT>=26) startForegroundService(new android.content.Intent(this,BluettiPersistentService.class)); else startService(new android.content.Intent(this,BluettiPersistentService.class)); }catch(Exception e){} }
    int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);} 
    GradientDrawable bgRound(int color, int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
    GradientDrawable bgStroke(int color, int radius, int strokeColor){GradientDrawable g=bgRound(color,radius);g.setStroke(dp(1),strokeColor);return g;}

    @Override TextView tv(String t,int sp,int c){TextView v=new TextView(this);v.setText(t);v.setTextSize(sp);v.setTextColor(c==Color.DKGRAY?muted:c);v.setPadding(dp(4),dp(3),dp(4),dp(3));if(sp>=18)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setSingleLine(false);return v;}
    @Override Button btn(String t){Button b=new Button(this);b.setText(t);b.setAllCaps(false);b.setTextColor(blue);b.setTextSize(12);b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);b.setMinHeight(dp(44));b.setPadding(dp(10),dp(4),dp(10),dp(4));b.setBackground(bgRound(Color.rgb(232,239,250),999));b.setElevation(dp(2));return b;}
    @Override LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(18),dp(18),dp(18));c.setBackground(bgStroke(white,28,Color.rgb(220,227,236)));c.setElevation(dp(7));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(dp(16),dp(10),dp(16),dp(10));c.setLayoutParams(lp);return c;}
    @Override TextView metric(String title){TextView v=tv(title+": --",15,text);v.setBackground(bgStroke(white,24,Color.rgb(220,227,236)));v.setElevation(dp(4));v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(16),dp(14),dp(16),dp(14));v.setMinHeight(dp(96));return v;}
    void two(LinearLayout p,View a,View b){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams lp1=new LinearLayout.LayoutParams(0,-2,1);lp1.setMargins(dp(6),dp(6),dp(6),dp(6));LinearLayout.LayoutParams lp2=new LinearLayout.LayoutParams(0,-2,1);lp2.setMargins(dp(6),dp(6),dp(6),dp(6));r.addView(a,lp1);r.addView(b,lp2);p.addView(r);} 
    void gridAdd(LinearLayout p, View... views){LinearLayout row=null;for(int i=0;i<views.length;i++){if(i%2==0){row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);p.addView(row);}LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.setMargins(dp(6),dp(6),dp(6),dp(6));row.addView(views[i],lp);} }
    TextView label(String s){TextView v=tv(s,11,muted);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setLetterSpacing(.08f);return v;}
    TextView chip(String s){TextView v=tv(s,10,greenDark);v.setGravity(Gravity.CENTER);v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);v.setBackground(bgStroke(Color.rgb(221,248,234),999,Color.rgb(180,236,206)));v.setPadding(dp(12),dp(4),dp(12),dp(4));return v;}
    void styleInput(EditText e){e.setTextColor(text);e.setHintTextColor(muted);e.setTextSize(14);e.setTypeface(Typeface.DEFAULT,Typeface.BOLD);e.setSingleLine(true);e.setMinHeight(dp(46));e.setPadding(dp(14),0,dp(14),0);e.setGravity(Gravity.CENTER_VERTICAL);e.setBackground(bgRound(Color.rgb(238,242,247),12));}

    @Override void buildUi(){
        ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);root.setPadding(0,dp(10),0,dp(28));sv.addView(root);
        LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setPadding(dp(16),0,dp(16),0);top.setBackgroundColor(Color.rgb(244,252,241));top.addView(tv("☰",24,text),new LinearLayout.LayoutParams(0,dp(64),1));TextView title=tv("BLUETTI",20,text);title.setGravity(Gravity.CENTER);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);top.addView(title,new LinearLayout.LayoutParams(0,dp(64),2));TextView gear=tv("⚙",22,text);gear.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);top.addView(gear,new LinearLayout.LayoutParams(0,dp(64),1));root.addView(top);

        LinearLayout hero=card();hero.setOrientation(LinearLayout.HORIZONTAL);hero.setGravity(Gravity.CENTER_VERTICAL);
        LinearLayout mid=new LinearLayout(this);mid.setOrientation(LinearLayout.VERTICAL);heroName=tv("BLUETTI",20,text);heroName.setTypeface(Typeface.DEFAULT,Typeface.BOLD);status=chip("Status: Aguardando");deviceTitle=tv("Dispositivo: --\nSN: --\nMAC: --",10,muted);mid.addView(heroName);mid.addView(status);mid.addView(deviceTitle);hero.addView(mid,new LinearLayout.LayoutParams(0,-2,1));
        LinearLayout right=new LinearLayout(this);right.setGravity(Gravity.CENTER);right.setOrientation(LinearLayout.VERTICAL);heroSoc=tv("--%",32,green);heroSoc.setGravity(Gravity.CENTER);heroSoc.setBackground(bgStroke(Color.WHITE,999,Color.rgb(230,236,245)));heroSoc.setPadding(dp(18),dp(18),dp(18),dp(18));right.addView(heroSoc,new LinearLayout.LayoutParams(dp(104),dp(104)));heroTime=tv("Sem consumo\n-- rest.",10,muted);heroTime.setGravity(Gravity.CENTER);right.addView(heroTime);hero.addView(right,new LinearLayout.LayoutParams(dp(120),-2));root.addView(hero);

        LinearLayout metrics=new LinearLayout(this);metrics.setOrientation(LinearLayout.VERTICAL);metrics.setPadding(dp(10),0,dp(10),0);gridAdd(metrics,stat("▮","Bateria","--%",green),stat("↯","Entrada","--W",blue),stat("⚡","Saída","--W",orange),stat("♁","DC","--V",purple));root.addView(metrics);
        battery=statBattery;acIn=statInput;acOut=statOutput;dcOut=statDc;dcIn=tv("Entrada DC: -- W",14,text);acState=tv("AC --",14,text);dcState=tv("DC --",14,text);
        batteryGraph=new GraphView(this,"",100);batteryGraph.setVisibility(View.GONE);consumptionGraph=new GraphView(this,"",1000);consumptionGraph.setVisibility(View.GONE);showBatteryGraph=new CheckBox(this);showConsumptionGraph=new CheckBox(this);

        LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.VERTICAL);controls.setPadding(dp(10),0,dp(10),0);Button acOn=powerButton("⏻  AC LIGAR",Color.rgb(221,248,234)),acOff=powerButton("♨  AC DESLIGAR",Color.rgb(255,226,226)),dcOn=powerButton("☷  DC LIGAR",Color.rgb(221,248,234)),dcOff=powerButton("☷  DC DESLIGAR",Color.rgb(255,226,226));gridAdd(controls,acOn,acOff,dcOn,dcOff);root.addView(controls);

        LinearLayout auto=card();auto.addView(tv("Automação",20,text));autoEnable=new CheckBox(this);autoEnable.setText("Ativar automação local");autoEnable.setTextColor(text);autoEnable.setTextSize(14);autoAc=new CheckBox(this);autoAc.setText("Automatizar AC");autoAc.setTextColor(text);autoAc.setTextSize(14);autoDc=new CheckBox(this);autoDc.setText("Automatizar DC");autoDc.setTextColor(text);autoDc.setTextSize(14);auto.addView(autoEnable);auto.addView(autoAc);auto.addView(autoDc);
        LinearLayout pair=new LinearLayout(this);pair.setOrientation(LinearLayout.HORIZONTAL);LinearLayout minBox=new LinearLayout(this);minBox.setOrientation(LinearLayout.VERTICAL);minBox.addView(label("MÍNIMO (%)"));lowPct=new EditText(this);lowPct.setHint("20");lowPct.setInputType(2);styleInput(lowPct);minBox.addView(lowPct);LinearLayout maxBox=new LinearLayout(this);maxBox.setOrientation(LinearLayout.VERTICAL);maxBox.addView(label("MÁXIMO (%)"));highPct=new EditText(this);highPct.setHint("80");highPct.setInputType(2);styleInput(highPct);maxBox.addView(highPct);pair.addView(minBox,new LinearLayout.LayoutParams(0,-2,1));pair.addView(maxBox,new LinearLayout.LayoutParams(0,-2,1));auto.addView(pair);
        auto.addView(label("INTERVALO (S)"));intervalSec=new EditText(this);intervalSec.setHint("30");intervalSec.setInputType(2);styleInput(intervalSec);auto.addView(intervalSec,new LinearLayout.LayoutParams(-1,-2));Button save=solidButton("▣  Salvar",greenDark),test=solidButton("▷  Testar",Color.rgb(0,90,193));two(auto,save,test);automationStatus=tv("Automação: desligada",13,muted);auto.addView(automationStatus);root.addView(auto);

        LinearLayout dev=card();dev.addView(tv("Outros Dispositivos",20,text));manualName=new EditText(this);manualName.setHint("Nome da Bluetti");styleInput(manualName);manualMac=new EditText(this);manualMac.setHint("MAC Bluetooth");styleInput(manualMac);dev.addView(manualName);dev.addView(manualMac);Button add=btn("Adicionar"),clear=btn("Limpar lista");two(dev,add,clear);savedBox=new LinearLayout(this);savedBox.setOrientation(LinearLayout.VERTICAL);dev.addView(savedBox);root.addView(dev);

        LinearLayout conn=card();conn.addView(tv("Conexão",20,text));Button scan=btn("Buscar"),stop=btn("Parar"),connect=btn("Conectar"),disconnect=btn("Desconectar"),refresh=btn("Atualizar"),reconnect=btn("Reconectar");gridAdd(conn,scan,stop,connect,disconnect,refresh,reconnect);root.addView(conn);
        list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);root.addView(list);LinearLayout log=card();log.addView(tv("Registros de Atividade",20,text));logBox=new LinearLayout(this);logBox.setOrientation(LinearLayout.VERTICAL);log.addView(logBox);root.addView(log);

        scan.setOnClickListener(v->startScan());stop.setOnClickListener(v->stopScan());connect.setOnClickListener(v->connectSelected());disconnect.setOnClickListener(v->disconnect());refresh.setOnClickListener(v->readStatus());reconnect.setOnClickListener(v->{disconnect();handler.postDelayed(this::connectSelected,800);});acOn.setOnClickListener(v->writeRegister(3007,1));acOff.setOnClickListener(v->writeRegister(3007,0));dcOn.setOnClickListener(v->writeRegister(3008,1));dcOff.setOnClickListener(v->writeRegister(3008,0));add.setOnClickListener(v->addManualDevice());clear.setOnClickListener(v->{getSharedPreferences("devices",0).edit().clear().apply();renderSavedDevices();});save.setOnClickListener(v->{saveAutomation();applyAutomationState();});test.setOnClickListener(v->runAutomationCheck(true));setContentView(sv);
    }

    TextView stat(String icon,String label,String value,int color){TextView v=tv(icon+"  "+label.toUpperCase()+"\n"+value,18,color);v.setBackground(bgStroke(white,24,Color.rgb(220,227,236)));v.setElevation(dp(5));v.setGravity(Gravity.CENTER_VERTICAL);v.setPadding(dp(16),dp(14),dp(16),dp(14));v.setMinHeight(dp(96));if(label.equals("Bateria"))statBattery=v;else if(label.equals("Entrada"))statInput=v;else if(label.equals("Saída"))statOutput=v;else statDc=v;return v;}
    Button powerButton(String t,int color){Button b=btn(t);b.setTextColor(Color.BLACK);b.setTextSize(14);b.setMinHeight(dp(64));b.setBackground(bgStroke(color,22,Color.rgb(220,227,236)));b.setElevation(dp(4));return b;}
    Button solidButton(String t,int color){Button b=btn(t);b.setTextColor(Color.WHITE);b.setBackground(bgRound(color,12));b.setElevation(dp(4));return b;}

    @Override void parseRead(byte[] pkt){try{if(pkt==null||pkt.length<5)return;int bc=pkt[2]&255,words=bc/2;if(words<2)return;int[] w=new int[words];for(int i=0;i<words&&4+i*2<pkt.length;i++)w[i]=((pkt[3+i*2]&255)<<8)|(pkt[4+i*2]&255);runOnUiThread(()->{if(words>=8){int dci=w[0],aci=w[1],aco=w[2],dco=w[3];lastSoc=w[7];lastConsumption=aco+dco;int inputTotal=aci+dci;heroSoc.setText(lastSoc+"%");statBattery.setText("▮  BATERIA\n"+lastSoc+"%");statInput.setText("↯  ENTRADA\n"+inputTotal+"W");statOutput.setText("⚡  SAÍDA\n"+lastConsumption+"W");statDc.setText("♁  DC\n"+dco+"W");heroTime.setText((lastConsumption>0?formatMinutes((1152*lastSoc/100*60)/Math.max(1,lastConsumption)):"Sem consumo")+"\nTempo restante");setStatus("Conectado",green);runAutomationCheck(false);}else if(words==2){acValue=w[0];dcValue=w[1];}});}catch(Exception e){log("Parser seguro: "+e.getMessage());}}
    String formatMinutes(int min){if(min<=0)return "--";return (min/60)+"h "+(min%60)+"m";}
}
